version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  webapp .
      - docker tag web:1 981942040659.dkr.ecr.us-east-1.amazonaws.com/webapp
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 981942040659.dkr.ecr.us-east-1.amazonaws.com/webapp
      - echo images has been Pushed to the ECR registry!

